on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: List open issues
      run: gh issue list --state open --json number,title > issues.json
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Get release tag name
      run: echo "${{ github.event.release.tag_name }}" > tag.txt
    - name: Add tag to issues
      run: |
        while IFS= read -r line; do
          issue_number=$(echo "$line" | jq -r '.number')
          gh issue add-labels "$issue_number" --labels "${{ github.event.release.tag_name }}"
        done < issues.json
